# Site settings
title: Nataniel Martin
email: natmartin31@gmail.com
description: "// Mobile Developer //"


# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested


# Portfolio collection to handle easely my past and futur work
collections:
- portfolio