menu:
- {name: About Me, url: '#about'}
- {name: Skills, url: '#skills'}
- {name: Portfolio, url: '#portfolio'}
- {name: Links, url: '#links'}

skills:
- {name: Objective-C, level: 100%}
- {name: Javascript, level: 70%}
- {name: HTML/CSS, level: 60%}
- {name: Github, level: 90%}


portfolio:
- { title: "Quixmaster",
	description: "Quixmaster is photo sharing game, share with friends and ans",
	app_url: "https://geo.itunes.apple.com/us/app/quixmaster-challenge-your/id955856081?mt=8",
	img_url: "/assets/img/projectsIcons/quixmasterIcon.png",
	tags: [first project, blop, hello,first project, blop, hello,first project, blop, hello,first project, blop, hello] }

- { title: "Homme Elegant",
	description: "Help you find the best clothing shop around paris labeled homme elegant",
	app_url: "",
	img_url: "/assets/img/projectsIcons/hommeElegantIcon.png",
	tags: [yop, blop, hello] }

- { title: "TiZR",
	description: "Broacast to your friends the best live video around the world with tyour phone",
	app_url: "https://geo.itunes.apple.com/fr/app/tizr/id989806924?mt=8",
	img_url: "/assets/img/projectsIcons/tizhrIcon.png",
	tags: [yop, blop, hello] }

- { title: "InCity",
	description: "Be the green citizen in your city by reporting stuff in the street that can be fixed / cleaned",
	app_url: "",
	img_url: "/assets/img/projectsIcons/incityIcon.png",
	tags: [yop, blop, hello] }
