menu:
- {name: About Me, url: '#about'}
- {name: Skills, url: '#skills'}
- {name: Portfolio, url: '#portfolio'}
- {name: Links, url: '#links'}

skills:
- {name: skill 1, level: 5}
- {name: skill 2, level: 2}
- {name: skill 3, level: 3}
- {name: skill 4, level: 1}
- {name: skill 5, level: 1}

portfolio:
- { title: "Quixmaster",
	description: "Quixmaster is photo sharing game, share with friends and answer 4 responses in 10 secdons",
	url: "http://textl.com",
	img_url: "/assets/img/projectsIcons/quixmasterIcon.png" }

- { title: "Homme Elegant",
	description: "Help you find the best clothing shop around paris labeled homme elegant",
	url: "http://textl.com",
	img_url: "/assets/img/projectsIcons/hommeElegantIcon.png" }

- { title: "TiZR",
	description: "Broacast to your friends the best live video around the world with tyour phone",
	url: "http://textl.com",
	img_url: "/assets/img/projectsIcons/tizhrIcon.png" }

- { title: "InCity",
	description: "Be the green citizen in your city by reporting stuff in the street that can be fixed / cleaned",
	url: "http://textl.com",
	img_url: "/assets/img/projectsIcons/incityIcon.png" }
