menu:
- {name: About Me, url: '#about'}
- {name: Skills, url: '#skills'}
- {name: Portfolio, url: '#portfolio'}
- {name: Links, url: '#links'}

skills:
- {name: Objective-C, level: 100%}
- {name: Javascript, level: 70%}
- {name: HTML/CSS, level: 60%}
- {name: Github, level: 90%}


portfolio:

- { title: "TiZR",
	description: "Livestream fun stuff to your friends all around the world",
	app_url: "https://geo.itunes.apple.com/fr/app/tizr/id989806924?mt=8",
	img_url: "/assets/img/projectsIcons/tizhrIcon.png",
	tags: [Wowza, streaming, rtmp, MPMovieController, custom animations, push notifications, Parse, Cloud Code] }

- { title: "Homme Elegant",
	description: "Find your nearest tailor shop and suit up !",
	app_url: "https://geo.itunes.apple.com/fr/app/elegant-lapplication-faite/id1019533987?mt=8",
	img_url: "/assets/img/projectsIcons/hommeElegantIcon.png",
	tags: [Custom server] }

- { title: "InCity",
	description: "Be the super hero of modern times, report broken stuff to your local town",
	app_url: "",
	img_url: "/assets/img/projectsIcons/incityIcon.png",
	tags: [Google maps, fixmystreet API] }

- { title: "Quixmaster",
	description: "Test your friends by creating your own quizz with a picture",
	app_url: "https://geo.itunes.apple.com/us/app/quixmaster-challenge-your/id955856081?mt=8",
	img_url: "/assets/img/projectsIcons/quixmasterIcon.png",
	tags: [first project, Parse] }

links:
- { url: "https://github.com/havocked",
	title: "Github",
	icon_url: "/assets/img/linksIcons/github.png"}

- { url: "http://stackoverflow.com/users/1095988/mindhavok",
	title: "stackoverflow",
	icon_url: "/assets/img/linksIcons/stackoverflow.png"}

- { url: "https://www.linkedin.com/in/natanielmartin",
	title: "linkedin",
	icon_url: "/assets/img/linksIcons/linkedin.png"}
